### ISSUE TITLE
tm1_target.cells.write dont work with attribut of a dimension

### ISSUE THREAD

**Issue by farevian** [MariusWirtz/tm1py-tales#3]
Hello,

Try to use https://cubewise-code.github.io/tm1py-tales/2021/sync-dimensions.html. The cells.write return an error in cellService.py, function write_throuh_unbound_process ligne 504. Look like the element is alway see as numeric even it's a string. If I try a write_value, get an error saying that the element is not found in the collection (ligne 103 of the module). I use TM1Py 1.6.

Regards

**Comment by MariusWirtz** [comment]
Thanks for resporting.

Please post your code and the full stack trace of the error message.

**Comment by farevian** [comment]
Hello, 
The files. 2 files because I use QT5.
[Utilitaires_tm1.zip](https://github.com/cubewise-code/tm1py-tales/files/7052003/Utilitaires_tm1.zip)

And the stack :

runfile('C:/Utilitaires_tm1/LivreDimCode.py', wdir='C:/Utilitaires_tm1')
Reloaded modules: LivreDimension
Traceback (most recent call last):

  File "C:\Utilitaires_tm1\LivreDimCode.py", line 272, in livre
    servDest.cells.write(cube_name = attribCube,

  File "C:\Anaconda3\lib\site-packages\TM1py\Services\CellService.py", line 420, in write
    return self.write_through_unbound_process(

  File "C:\Anaconda3\lib\site-packages\TM1py\Utils\Utils.py", line 26, in wrapper
    return func(self, *args, **kwargs)

  File "C:\Anaconda3\lib\site-packages\TM1py\Services\CellService.py", line 78, in wrapper
    return func(self, *args, **kwargs)

  File "C:\Anaconda3\lib\site-packages\TM1py\Services\CellService.py", line 503, in write_through_unbound_process
    value_str = format(value, f'.{precision}f')

TypeError: unsupported format string passed to dict.__format__

Regards

**Comment by MariusWirtz** [comment]
Judging by the error message I think you need to upgrade to the last version of TM1py.

try this: `pip install tm1py --upgrade`

**Comment by farevian** [comment]
Hello, 
I see that new version is on github. Is it on this version ? I can't use PIP at work, proxy block evry access. I can download source

**Comment by farevian** [comment]
Hello, I install the 1.7 version and have same problème. As I look in Cellservice.py on ligne 610 you call 
**element_type = measure_dimension_elements.get(coordinates[-1], 'Numeric')** but if I look for coordinates[-1] I find 
[}ElementAttributes_Activities_G].[}ElementAttributes_Activities_G].[Libelle]. I think that you want to send Libelle to the function to get from the dictionnary the value 'String' as the dictionnay contain : String for element[1] for libelle (hop I m clear). 
Has the key passed is wrong, the code alway try to put a numeric as it's a string in this case.

Regards

**Comment by farevian** [comment]
Done the correction replace the ligne by
element_type = measure_dimension_elements.get(coordinates[-1].split('.')[-1][1:-1], 'Numeric')

And it work
regards

**Comment by MariusWirtz** [comment]
Hi @farevian,

sorry for the late reply. This is not an error in TM1py. The dictionary that is passed into write_through_unbound_process as the `cells` argument is expected to have the below shape:

```
{
('e1', 'e2', 'e3): 1,
('e1', 'e2', 'e3): 2
}
```

Somehow you are passing a dictionary with element unique names as keys into the function. I think the error lies elsewhere.

I a recent change to TM1py we introduced `element_unique_names` and the `skip_cell_properties` argument. Make sure you include those in the previous step

``` python
        attribute_cells = tm1_source.cells.execute_mdx(
            mdx=mdx,
            element_unique_names=False,
            skip_cell_properties=True,
            skip_rule_derived_cells=True)
```

**Comment by farevian** [comment]
I will try to be sure that element_unique_names was at False not sur but I think it was at False, because I was not knowing the option and I copy the code from the exemple. 
Regards

**Comment by farevian** [comment]
test done and OK. I thing that the MdxBuilder was not the last version. I close the case
